# Generated by Django 2.1.7 on 2020-01-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ammount',
            field=models.IntegerField(default=0),
        ),
    ]
