# Generated by Django 2.1.7 on 2021-01-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_ammount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
